# Site settings
title:          KeepJS
description:    "javascript blog"
baseurl:        ""
url:            "https://kjcvbn.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         JongChan Kim
  url:          https://kjcvbn.github.io
  email:        kjcvbn@gmail.com

# github
github:       "https://www.github.com/kjcvbn"

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# disqus
disqus_shortname: kjcvbn-github-io
